<?php

$finder = Symfony\CS\Finder\DefaultFinder::create()
    ->exclude([
        'vendor'
    ])
    ->in(__DIR__);

return Symfony\CS\Config\Config::create()
    ->level(Symfony\CS\FixerInterface::PSR2_LEVEL)
    ->setUsingCache(true)
    ->fixers(array(
        '-psr0',
        '-psr4',
        'encoding',
        'short_tag',
        'elseif',
        'blankline_after_open_tag',
        'namespace_no_leading_whitespace',
        'no_blank_lines_after_class_opening',
        'single_array_no_trailing_comma',
        'no_empty_lines_after_phpdocs',
        'concat_with_spaces',
        'function_call_space',
        'function_declaration',
        'eof_ending',
        'ordered_use',
        'extra_empty_lines',
        'single_line_after_imports',
        'trailing_spaces',
        'remove_lines_between_uses',
        'return',
        'indentation',
        'linefeed',
        'braces',
        'visibility',
        'unused_use',
        'whitespacy_lines',
        'php_closing_tag',
        'phpdoc_order',
        'phpdoc_params',
        'phpdoc_trim',
        'phpdoc_scalar',
        'phpdoc_short_description',
        'phpdoc_no_empty_return',
        'phpdoc_indent',
        'phpdoc_type_to_var',
        'phpdoc_var_without_name',
        'short_array_syntax',
        'align_double_arrow',
        'align_equals',
        'lowercase_constants',
        'lowercase_keywords',
        'multiple_use',
        'line_after_namespace',
        'method_argument_space',
        'parenthesis',
        'unary_operators_spaces',
        'multiline_array_trailing_comma',
    ))->finder($finder);