name: Bug Report
description: Report a general package issue. Filling in the issue template is mandatory, issues without it will be closed. Please ensure your Laravel-Excel version is still supported (Currently ^3.1)
title: "[Bug]: "
labels: [bug]
body:
- type: checkboxes
  id: terms
  attributes:
    label: Is the bug applicable and reproducable to the latest version of the package and hasn't it been reported before?
    description: Currently 3.1.x
    options:
    - label: Yes, it's still reproducable
      required: true     
- type: input
  attributes:
   label: What version of Laravel Excel are you using?
   description: 'For example: 3.1.30'
  validations:
     required: true
- type: input
  attributes:
    label: What version of Laravel are you using?
    description: 'For example: 7.1.10'
  validations:
        required: true
- type: input
  attributes:
    label: What version of PHP are you using?
    description: 'For example: 8.1.0'
  validations:
      required: true  
- type: textarea
  attributes:
    label: Describe your issue
    description: Describe the problem you're seeing, Please be short, but concise.
  validations:
    required: true  
- type: textarea
  attributes:
    label: How can the issue be reproduced?
    description: Please provide easy-to-reproduce steps (repository, simple code example, failing unit test). Please don't paste your entire code, but create a reproducable scenario that can be tested using a simple User model in a blank Laravel installation.
  validations:
    required: true  
- type: textarea
  attributes:
    label: What should be the expected behaviour?
    description: Please describe what the expected outcome should be. Any suggestions to what is wrong?
  validations:
    required: true  
