name: Run tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: laravel_excel
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: false
      matrix:
        php: [ 8.2, 8.3, 8.4, 8.5 ]
        laravel: [ 12, 11 ]
        dependency-version: [ prefer-stable ]
        os: [ ubuntu-latest ]
        include:
          - laravel: 12
            scout: 10.*
            testbench: 10.*
          - laravel: 11
            scout: 10.*
            testbench: 9.*
        exclude:
          - laravel: 12
            php: 8.1
          - laravel: 11
            php: 8.5
          - laravel: 11
            php: 8.1
          - laravel: 10
            php: 8.4

    name: PHP${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependency-cache-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, mysql, pdo_mysql, bcmath, intl, gd, exif, iconv
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}.*" "orchestra/testbench:${{ matrix.testbench }}" "laravel/scout:${{ matrix.scout }}"  --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --testdox --configuration phpunit.xml.dist
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
